### ISSUE TITLE
Option for running program when starting 

### ISSUE THREAD

**Issue by acadet** [thomasfl/filewatcher#17]
Hi there,

I would like to know if it is possible to add an option to your program. This option would run provided command when starting `filewatcher`.

Thanks :)

**Comment by thomasfl** [comment]
I am not certain I understand what you mean. Could you provide some examples.

Cordialment Thomas ;-)

**Comment by acadet** [comment]
Sorry for this poor explanation then.

I would like to have an option for running command immediately when starting watching. Obviously, no file would have been edited.

For instance, I like using your gem for running Rails tests automatically: 

```
filewatcher *.rb "rspec -fd"
```

However, if I run this command, I need to update a file for running my tests a first time. I would like to execute `rspec -fd` as soon as I have started `filewatcher`. Such as a `run_at_begin` option.

**Comment by thomasfl** [comment]
I've thinking about this myself actually. It's a good idea to implement it as an option. I think --run-at-startup or --exec-at-startup is a more suitable name though.

**Comment by thomasfl** [comment]
I think it's even better to name the option  `--dontwait'. It's a problem that filewatcher sets the environment variable  `$FILENAME' before running the command, but if filewatcher was started with the `--dontwait' no changes has been done to the filesystem yet. One way of solving this, is to set '$FILENAME' to the first file in the list of files it is listening for changes in. In reality I don't think this is going to be a big problem though.

The same goes for the ruby API. Filewatcher simply could set filename and event to nil inside to the filewatcher code block.

**Comment by thomasfl** [comment]
The '--dontwait' option is implemented and pushed to rubygems.org.

**Comment by thomasfl** [comment]
@acadet I was thinking about renaming the --restart option to --background, since it runs the shell commands in the background. Any opinions?
