### ISSUE TITLE
Support interruptions

### ISSUE THREAD

**Issue by acadet** [thomasfl/filewatcher#18]
Hi again :)

Another cool enhancement would be to support interruptions. Currently, you queue a new process when any file has been edited, meanwhile command is running. Do you think it would be possible to add an option to force command interruption if any notification is incoming?

**Comment by thomasfl** [comment]
That's a great idea. It would be natural to name such an option -r/--restart

This could be used to send a kill 9/SIGHUP to a webserver and then start the webserver again every time some change in the filesystem happens.

     $ filewatcher "**/*.js" --restart "ruby sinatra"

**Comment by thomasfl** [comment]
@acadet I have released a new version of filewatcher with new `--dontwait` and `--restart` options. Now you should be able to use it to start a webserver and have it restarted on file updates.

    $ filewatcher --restart --dontwait "**/*.html" "python -m SimpleHTTPServer"

Please let me know if you have any problems.

BTW! I think this is a real cool functionality.

**Comment by thomasfl** [comment]
@acadet  @flbulgarelli  @oldpatricka  @noplay @kitofr I have pushed a new version of the filewwatcher gem today that can automatically restart long running processes, like web servers like this:

    $ filewatcher --restart --dontwait "**/*.html" "python -m SimpleHTTPServer"

I was thinking about making automatic restart default behaviour in filewatcher. That means filewatcher won't wait for long running tests to finish if source files are updated. I don't know if this behaviour is desired. The advantage is that you don't have to remember any filewatcher switches to make it auto reload for instance a sinatra app.

    $ filewatcher "**/*.html" "ruby my_sinatra_app.rb"

Comments would be highly appreciated! :-)

**Comment by acadet** [comment]
Hey Thomas,

It works fine. You can upgrade `filewatcher` to make this option as default. However, I definitively think you should allow user to change behaviour if s/he wish ;)

Besides, I have noticed that, from now on, you need to surround file pattern to watch with quotes, whereas, before, this was not required.

Anyway, keep going like that man. Your gem is fantastic and really useful :)

**Comment by thomasfl** [comment]
Hi Adrien,

I too think that the default behaviour of filewatcher should be to restart the running process started be filewatcher. This is convenient when running tests and off course when you are running a webserver.

Instead of having an option called `--restart', instead there should be an option called '--wait-to-finish`, a hurry option that takes an argument `--hurry false|true', or have an restart option that takes an argument `--restart true|false`.

**Comment by acadet** [comment]
You should keep it simple. If `--restart` option has been provided, restart as soon as a watched file has been edited. Otherwise, run `filewatcher` using your default behaviour ;)
Ditto for `--hurry` (run command on start).

It could be the opposite, obviously, it's up to you. However, just spot if option has been provided or no. Investigating value is more complex, in my opinion.

**Comment by thomasfl** [comment]
Implemented. Thanks to @acadet for this great idea. I use it myself everyday.
