### ISSUE TITLE
any way to get pid of invocation?

### ISSUE THREAD

**Issue by sandric** [thomasfl/filewatcher#19]
Hi, I struggling with getting file events showing pid (and process name) who invoked change to file. For example, set filewatchet to display vim if I changed watched file via vim. Is it even possible? thx.

**Comment by thomasfl** [comment]
Why do you want to do that? I may help you if I knew the reason why.

If you want to kill a process, filewatcher tecently got a new --restart boolean option.

**Comment by sandric** [comment]
@thomasfl to be able to monitor fs events with ability to see process who makes event. Just like auditd or loggedfs do. The problem is that auditd is too slow and loggedfs is too buggy.

**Comment by thomasfl** [comment]
@sandric There is a unix command called ```lsof```` which lists open files, but it doesn't always work as excpected. I've never used it.
