### ISSUE TITLE
Deleting directory containing watched file would cause exception

### ISSUE THREAD

**Issue by flyfy1** [thomasfl/filewatcher#25]
How to replicate:

1. `filewatcher '**/*.t' 'echo got file: $FILENAME'`
2. `mkdir test`
3. `touch test/haha.t`
4. `rm -R test`

Then exception would be thrown: 

    gems/filewatcher-0.5.1/bin/filewatcher:108:in `realpath': No such file or directory @ realpath_rec - /home/songyy/fswatch (Errno::ENOENT)

**Comment by thomasfl** [comment]
Thanks a lot Song Yangyu for taking the time to report this bug. 

When a file is changed, it's real absolute path is determined and exported as the environment variable $FILEDIR. The method for determening the real absolute path was unsafe, and has been replaced by something more robust.

A new version of filewatcher has been pushed to rubygems.
