### ISSUE TITLE
Filewatcher reporting moved files in the order (changed) -> new -> delete

### ISSUE THREAD

**Issue by peekxc** [thomasfl/filewatcher#26]
Hi. I'm trying to write a small directory watcher using your utility through the Ruby API, using OS X 10.11. 

Something as simple as... 

FileWatcher.new("lib/").watch(1) do |filename, event|
  puts event.to_s
end

...reports file moves, like dragging and dropping a file between directories within "lib" first as "new" and then later as "delete" consistently, regardless of changing the watch interval. This is causing me problems with watching files for the sake of creating symbolic links.  

In the docs, you mentioned: "When a file is renamed it is detected as a deletion followed by a file addition."--is that rule supposed to extend to file moves as well?

**Comment by thomasfl** [comment]
Yes! Filewatcher currently only checks two things, namely filenames and their timestamp. It is done by simply scanning the filesystem every second. To detect renaming and moving, filewatcher needs to check the files id's as well. If you like to take on the challenge, then you're welcome to submit a pull request. :-)

**Comment by peekxc** [comment]
I see, thank you :)
