### ISSUE TITLE
$FILENAME returns nothing

### ISSUE THREAD

**Issue by chelog** [thomasfl/filewatcher#30]
Hello, I've met this problem when using CLI:
```
filewatcher -l "here.txt" "echo $FILENAME was edited"
Watching:
 here.txt
was edited
was edited
was edited
```

Any ideas of what can be wrong?

**Comment by nbekirov** [comment]
Compare these:

### Single quotes
```bash
$ export FILENAME='other.txt'
$ filewatcher -l something.txt 'echo File: $FILENAME was edited'
Watching:
 something.txt
File: something.txt was edited
```

### Double quotes
```bash
$ export FILENAME='other.txt'
filewatcher -l something.txt "echo File: $FILENAME was edited"
Watching:
 something.txt
File: other.txt was edited
```

You can also read this article to see more examples [What’s the Difference Between Single and Double Quotes in the Bash Shell?](http://www.howtogeek.com/howto/29980/whats-the-difference-between-single-and-double-quotes-in-the-bash-shell/)

**Comment by thomasfl** [comment]
Thanks for answering this @nbekirov The examples in the readme file also uses single quotes on non-windows machines.

**Comment by chelog** [comment]
@nbekirov @thomasfl oh well, my bad... always got confused with these quotes in Unix scripting
Thank you! Especially for the article
