### ISSUE TITLE
Export $BASENAME variable

### ISSUE THREAD

**Issue by thomasfl** [thomasfl/filewatcher#31]
If $FiLENAME is "hello.js" or "hello.ts", then $BASENAME should be "hello".

This should be useful when running compiled code. Example

```
    $ filewatcher "*.ts" "tsc $FILENAME;node $BASENAME.js"
```

**Comment by AlexWayfer** [comment]
```
$ filewatcher "*.ts" "tsc $FILENAME;node $(basename $BASENAME .ts).js"
```

What do you think about this approach?

**Comment by thomasfl** [comment]
If it works, the approach is ok.

**Comment by AlexWayfer** [comment]
Yes, it works.

And there are many [other ways](http://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash) do it, shell-specifically, or (as I wrote) shell-agnostic:

```
$ basename --help
Usage: basename NAME [SUFFIX]
  or:  basename OPTION... NAME...
Print NAME with any leading directory components removed.
If specified, also remove a trailing SUFFIX.

Mandatory arguments to long options are mandatory for short options too.
  -a, --multiple       support multiple arguments and treat each as a NAME
  -s, --suffix=SUFFIX  remove a trailing SUFFIX; implies -a
  -z, --zero           end each output line with NUL, not newline
      --help     display this help and exit
      --version  output version information and exit

Examples:
  basename /usr/bin/sort          -> "sort"
  basename include/stdio.h .h     -> "stdio"
  basename -s .h include/stdio.h  -> "stdio"
  basename -a any/str1 any/str2   -> "str1" followed by "str2"

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Full documentation at: <http://www.gnu.org/software/coreutils/basename>
or available locally via: info '(coreutils) basename invocation'
```

And I think that dynamically behavior of `$BASENAME` is wrong approach. It must be consistent and predicable.

**Comment by thomasfl** [comment]
Yes, it seems like gnu basename differs from ruby basename (https://ruby-doc.org/core-2.2.0/File.html#method-c-basename). Do you have any suggestions on how to make $BASENAME more linux/gnu compliant? The simplest solution is perhaps to not export any BASENAME variable at all, I guess.

**Comment by AlexWayfer** [comment]
> Yes, it seems like gnu basename differs from ruby basename (https://ruby-doc.org/core-2.2.0/File.html#method-c-basename).

With `-s` option, or without options at all, they are very similar :)

> Do you have any suggestions on how to make $BASENAME more linux/gnu compliant? The simplest solution is perhaps to not export any BASENAME variable at all, I guess.

I think that the current implementation of the `$BASENAME` is ok: who wants to - can use (possibly with external modifications), who doesn't want - will not, or take another variable (`$FILENAME`, for example).
