### ISSUE TITLE
Is there an option to get only the last file of the new files added to a folder.

### ISSUE THREAD

**Issue by demonmind** [thomasfl/filewatcher#34]
I need to get just the last file added if there is an event, but if i add 6 files it will just get all of those and fire the event on each of the files.

**Comment by nbekirov** [comment]
I think that there is not really such thing as "add 6 files" as a simultaneous event - you create those files one after another and this might take some time greater than the default [interval](https://github.com/thomasfl/filewatcher#command-line-options) (For example if have a loop that makes 6 external calls 1 second each to get some info and put the results in 6 different files).

Maybe you can try to:
* specify the interval based on what your expected running time is
* aggregate the notifications in something like environment variable/file by constantly overwriting it

**Comment by thomasfl** [comment]
Yes, you need to watch a set of changes within a specified time interval. Just out of curiosity, what do you want to use this for?

**Comment by demonmind** [comment]
I am using this for a ComputerVision project in my class.

The camera detects motion and uploads to an ftp server 6 images of the object that triggered the motion on the camera. I want to just use the last image of the 6 because thats the most clear one.

Then i will upload it to a server and send the email with the picture to the person.

**Comment by nbekirov** [comment]
Isn't there any pattern in the file name that may help you narrow what you are watching for like `filewatcher '*-6.jpeg' 'echo $FILENAME'`?

**Comment by demonmind** [comment]
Yes I am using that one now.
