### ISSUE TITLE
Daemonize

### ISSUE THREAD

**Issue by AlexWayfer** [thomasfl/filewatcher#35]
Hello!

How can I run `filewatcher` in background?

My case:

```ruby
#!/usr/bin/env ruby

def bash(command)
  system "bash -c \"#{command}\""
end

bash "filewatcher 'some_files' 'some_command' &"
bash "tail -f some_log_file"
```

When I press Ctrl+C in `tail` — `filewatcher` is also stopping.

I want to stop `tail`, but not `filewatcher`.

Thanks!

**Comment by thomasfl** [comment]
The --restart option makes filewatcher run the command supplied as a parameter in the background:

```
    $ filewatcher --restart  "**/*.html" "webserver"
```

Every time an html file changes, filewatcher will kill the webserver process and start it again in a new process.

So if you want to run filewatcher in the background, you can actually supply filewatcher as a command to filewatcher itself. I haven't tested this, but it may look something like this:

```
    $ filewatcher --restart  "**/*.html" "$ filewatcher --restart  '**/*.html' 'tail -f some_log_file'"
```

If you wan't to get some hints on how to run things in the background, please have a look at 

https://github.com/thomasfl/filewatcher/blob/master/bin/filewatcher

Processes are run in the background simply by using

```
  pid = Process.spawn(env, cmd)
```

I have to admit I am not sure what you are trying to accomplish.

**Comment by AlexWayfer** [comment]
Okay, that's example for my case:
```ruby
#!/usr/bin/env ruby

def bash(command)
	system "bash -c \"#{command}\""
end

def server(command)
	pumactl = "pumactl #{command} -F config/puma.rb"
	bash pumactl
	return unless %i(start restart).include?(command) && environment == 'development'
	bash 'pkill -f filewatcher'
	bash "filewatcher '**/*.{rb,ru,yml}' '#{pumactl}' > /dev/null &"
end

def monitor_server
	bash "tail -f log/{stdout,stderr} -q"
end

## Runtime
case ARGV[0]
when 'start'
	server :start
when 'stop'
	server :stop
when 'restart'
	server :restart
when 'monitor'
	monitor_server
when 'devel'
	server :restart
	puts 'Waiting for logs...'
	sleep 2
	monitor_server
end

```

**Comment by AlexWayfer** [comment]
Processes without daemonizing binds to Ruby script, as I think (also with `&`, or `Process.spawn`). So… When I press `Ctrl+C` — it's stop all binded processes too. But… I want to stop `tail`, not `filewatcher`. It's must be self-daemonizing, as I think (as `puma`) for that. But how? Or is there some workarounds?

**Comment by AlexWayfer** [comment]
Maybe [that](http://ruby-doc.org/core-2.3.1/Process.html#method-c-daemon) can be some helpful for your gem?
