### ISSUE TITLE
Code style improvements

### ISSUE THREAD

**Issue by AlexWayfer** [thomasfl/filewatcher#37]
Hello!

I saw that the syntax highlight for Markdown files is broken in Atom Editor, and would like to correct the syntax without changing the appearance.

Also saw lots of warnings from [Rubocop](https://github.com/bbatsov/rubocop), and would like to fix this (without adding functionality, bug fixing or replacing spaces with tabs).

What do you think about this?

**Comment by thomasfl** [comment]
Yes, please feel free to send pull requests where both the markdown and the ruby is refactored.

**Comment by AlexWayfer** [comment]
I still plan to do it 😔

**Comment by thomasfl** [comment]
Sorry Alex. Reopening issue. :-)

**Comment by AlexWayfer** [comment]
I look at it and remember every day. Will try on the weekend to find the time. Sorry for the delay.
