### ISSUE TITLE
RVM 2.3.2 Ruby 2.0.0 crashes upon use of filewatcher

### ISSUE THREAD

**Issue by daBee** [thomasfl/filewatcher#41]
I'm trying to invoke filewatcher using `kk`

    alias kk="filewatcher '~/app.rb' 'app'"
    alias app="clear; ruby ~/app.rb"

RVM has 2.3.2 chosen to `use` and as `--default`.  `Ruby -v` indicates just that.  Upon `kk`, Ruby 2.0.0 crashes for some reason.  I'm not sure why.  `app.rb` is a very simple file and runs in the terminal just fine.  

HQ:~ rich$ filewatcher "~/app.rb" "app"
```
/Users/rich/.rvm/gems/ruby-2.3.2/gems/psych-2.2.0/lib/psych.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0038 p:-17579991633118 s:0182 e:000181 TOP    [FINISH]
c:0037 p:---- s:0180 e:000179 CFUNC  :require
c:0036 p:0115 s:0176 e:000175 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0035 p:0028 s:0166 e:000165 TOP    /Users/rich/.rvm/gems/ruby-2.3.2/gems/psych-2.2.0/lib/psych.rb:7 [FINISH]
c:0034 p:---- s:0164 e:000163 CFUNC  :require
c:0033 p:0115 s:0160 e:000159 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0032 p:0078 s:0150 e:000149 METHOD /Library/Ruby/Site/2.0.0/rubygems.rb:601
c:0031 p:0013 s:0146 e:000145 METHOD /Library/Ruby/Site/2.0.0/rubygems/config_file.rb:327
c:0030 p:0145 s:0140 e:000139 METHOD /Library/Ruby/Site/2.0.0/rubygems/config_file.rb:196 [FINISH]
c:0029 p:---- s:0129 e:000128 CFUNC  :new
c:0028 p:0031 s:0125 e:000124 METHOD /Library/Ruby/Site/2.0.0/rubygems.rb:289
c:0027 p:0016 s:0122 e:000121 METHOD /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:63
c:0026 p:0181 s:0113 e:000112 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/ext/ext_conf_builder.rb:37
c:0025 p:0026 s:0105 e:000104 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:324
c:0024 p:0050 s:0100 e:000099 METHOD /Library/Ruby/Site/2.0.0/rubygems/ext/ext_conf_builder.rb:17
c:0023 p:0027 s:0089 e:000088 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:161 [FINISH]
c:0022 p:---- s:0087 e:000086 CFUNC  :chdir
c:0021 p:0015 s:0083 e:000082 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:160 [FINISH]
c:0020 p:---- s:0081 e:000080 CFUNC  :synchronize
c:0019 p:0123 s:0078 e:000077 METHOD /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:159
c:0018 p:0022 s:0068 e:000067 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:198 [FINISH]
c:0017 p:---- s:0065 e:000064 CFUNC  :each
c:0016 p:0108 s:0062 e:000061 METHOD /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:195
c:0015 p:0026 s:0058 e:000057 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1436
c:0014 p:0020 s:0055 e:000054 METHOD /Library/Ruby/Site/2.0.0/rubygems/user_interaction.rb:45
c:0013 p:0216 s:0050 e:000049 METHOD /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1434
c:0012 p:0037 s:0046 e:000045 METHOD /Library/Ruby/Site/2.0.0/rubygems/stub_specification.rb:60
c:0011 p:0007 s:0043 e:000042 METHOD /Library/Ruby/Site/2.0.0/rubygems/basic_specification.rb:56
c:0010 p:0019 s:0038 e:000037 BLOCK  /Library/Ruby/Site/2.0.0/rubygems/specification.rb:925 [FINISH]
c:0009 p:---- s:0035 e:000034 IFUNC
c:0008 p:---- s:0033 e:000032 CFUNC  :each
c:0007 p:---- s:0031 e:000030 CFUNC  :find
c:0006 p:0009 s:0028 e:000027 METHOD /Library/Ruby/Site/2.0.0/rubygems/specification.rb:924
c:0005 p:0017 s:0023 e:000022 METHOD /Library/Ruby/Site/2.0.0/rubygems.rb:185
c:0004 p:0050 s:0018 e:000017 RESCUE /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:132
c:0003 p:0444 s:0015 e:000014 METHOD /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144
c:0002 p:0079 s:0005 E:001940 EVAL   /Users/rich/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:9 [FINISH]
c:0001 p:0000 s:0002 E:002218 TOP    [FINISH]
```

**Comment by thomasfl** [comment]
Maybe there is some useful info in the log files:

   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports

**Comment by daBee** [comment]
Seems to be using 2.0.0 for some reason.  Not sure why.

**Comment by thomasfl** [comment]
How about creating a script like this, so you have control over which version of ruby you're running?

```
  #!/bin/sh
 /bin/ruby2.1.0/bin/ruby /path/to/filewatcher '~/app.rb' 'app'
```

**Comment by daBee** [comment]
New terminal window with the proper responding `which ruby`.  This is what happens upon `filewatcher "/users/rich/app.rb" "app"`

    rich$ filewatcher "/users/rich/app.rb" "app"
    /Users/rich/.rvm/gems/ruby-2.3.2/gems/filewatcher-0.5.3/bin/filewatcher:145:in `spawn': No such file or directory - app (Errno::ENOENT)
	from /Users/rich/.rvm/gems/ruby-2.3.2/gems/filewatcher-0.5.3/bin/filewatcher:145:in `block in <top (required)>'
	from /Users/rich/.rvm/gems/ruby-2.3.2/gems/filewatcher-0.5.3/lib/filewatcher.rb:60:in `watch'
	from /Users/rich/.rvm/gems/ruby-2.3.2/gems/filewatcher-0.5.3/bin/filewatcher:95:in `<top (required)>'
	from /Users/rich/.rvm/gems/ruby-2.3.2/bin/filewatcher:22:in `load'
	from /Users/rich/.rvm/gems/ruby-2.3.2/bin/filewatcher:22:in `<main>'
	from /Users/rich/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rich/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `<main>'

This issue seems to be migrating.

**Comment by daBee** [comment]
I got it to work:

    filewatcher "/users/rich/app.rb" "clear; ruby ~/app.rb"

**Comment by thomasfl** [comment]
Great! I can actually remember having the same problems some years ago when I first wrote this. You can also use the execute switch: -e. If the file extension is .rb then a ruby interpreter will execute ut. Actually this option is one of the features I've seriously have considered removing, since it's hardly being used.

**Comment by daBee** [comment]
Well the first parameter is the filesystem part, which I know little about.  I'm assuming that's just a trigger coming from the filesystem.  Second parameter has its own execution (ruby) in the command.  What would be useful is if the command could know about .bash_profile aliases, as in my case, it didn't know my alias `app` which is the command I was needing.
