### ISSUE TITLE
Add throttling support

### ISSUE THREAD

**Issue by gisikw** [thomasfl/filewatcher#43]
Absolutely love this tool - have run into an issue with my workflow that I suspect might be common to others as well.

Example usage:
```bash
filewatcher -r '**/*.rb' 'rubocop $FILENAME'
# in another terminal...
git checkout some-branch-with-multiple-changes
```

This will spawn a large number of rubocop instances (or whatever the dispatched process happens to be), which can end up causing CPU/memory issues if there are a lot of observed changes. Would be great to support a throttle value (perhaps only on the restart flag?), such that subsequent triggers within a small margin do not trigger a restart?

Unless the extra processes are potentially a bug? Just unclear as to whether or not it's intended behavior.

**Comment by thomasfl** [comment]
Thank's for the complement.

I guess that if you run this command, with a throttle value set to 10, then filewatcher would only spawn a new process every tenth second?

```
filewatcher --throttle 10 -r '**/*.rb' 'rubocop $FILENAME'
```
 
I've experienced similar problems myself.

**Comment by gisikw** [comment]
Actually, looked at this a bit more, and noticed there was an issue with the --restart flag that had it not reaping the child_pids consistently. PR #44 fixes that issue, so if a bunch of files change at once, the dispatch might start-and-stop a bunch while it queues through all the changes, but it won't cause extra child processes to be spawned. :)

**Comment by thomasfl** [comment]
Thank's for the PR @gisikw. A new version of this gem has been pushed to rubygems.org. Closing this issue.
