### ISSUE TITLE
How do I watch a directory for file changes and ignore directory changes?

### ISSUE THREAD

**Issue by pbrianmackey** [thomasfl/filewatcher#48]
I want to watch `C:/Git/MyProject` for changes to *.cshtml files.  I do not want to be notified about directory changes.  I tried this in powershell

```
filewatcher *.cshtml "C:/Git/MyProject" "rake myCommand %FILENAME%"
```

I'm getting 2 seperate hits.  One for the file that changed and another for the file's directory.

**Comment by AlexWayfer** [comment]
May be you must use

```
filewatcher "C:/Git/MyProject/*.cshtml" "rake myCommand %FILENAME%"
```

?

**Comment by pbrianmackey** [comment]
I used something similar `C:/Git/MyProject/**/*.cshtml`
