### ISSUE TITLE
Add support for tailing files

### ISSUE THREAD

**Issue by thomasfl** [thomasfl/filewatcher#69]
Seems like one of the key features of the filewatch gem, is the ability to tail files. This feature could be implemented as a separate gem that monkeypatches or extends filewatcher.

**Comment by AlexWayfer** [comment]
Why?

```
$ filewatcher '**/*' 'tail -f output_file'
```


_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thomasfl** [comment]
Hmm. So why is this gem so popular? https://github.com/jordansissel/ruby-filewatch

**Comment by AlexWayfer** [comment]
@thomasfl It is not more popular than `filewatcher`, as I can see. Just googling, or ignorance of UNIX commands.

_Sent from my Sony E5823 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AlexWayfer** [comment]
I think, we can close this issue?
