### ISSUE TITLE
String Interpolation...I think

### ISSUE THREAD

**Issue by daBee** [thomasfl/filewatcher#72]
I'm trying to sniff the latest log file for postgresql and tail that file.  Since it changes, I want to grab the last file and output tail:

    filewatcher "$(ls -t /var/db/postgres/data96/pg_log | head -1)" "tail -n 20 /var/db/postgres/data96/pg_log/$(ls -t /var/db/postgres/data96/pg_log | head -1)"

It resolves properly on its own, but not after filewatcher tries to use it.

**Comment by thomasfl** [comment]
I don't know if this will be of any help, but filewatcher exposes the environment variable FILENAME to the process executed each time the file system changes.

It also exposes these variables:
```
BASENAME           File basename.
FILENAME           Relative filename.
ABSOLUTE_FILENAME  Asolute filename.
RELATIVE_FILENAME  Same as FILENAME but starts with "./"
EVENT              Event type. Is either 'updated', 'deleted' or 'created'.
DIRNAME            Absolute directory name.
```

**Comment by daBee** [comment]
Update.  Turns out no files were changed.  My bad.
