### ISSUE TITLE
Ruby API Example update

### ISSUE THREAD

**Issue by riverswb** [thomasfl/filewatcher#73]
Hello, first off I'm a new developer and this is my first time opening an issue on an OS project so please be gentle!

The Ruby API examples show Filewatcher.new instead of FileWatcher.new:
```ruby

require 'filewatcher'

Filewatcher.new(['lib/', 'Rakefile']).watch do |filename|
  puts "Changed #{filename}"
end
```

Should be:

```ruby
require 'filewatcher'

FileWatcher.new(['lib/', 'Rakefile']).watch do |filename|
  puts "Changed #{filename}"
end

```

As in the gem file the class is defined as FileWatcher:

```ruby
class FileWatcher

  attr_accessor :filenames

  def self.VERSION
    return '0.5.4'
  end

```
I wouldn't make a comment if it was just one example, but all of the API examples are incorrect and it really threw me off for a while.

Thanks for this awesome gem!

**Comment by AlexWayfer** [comment]
Hello!

> Hello, first off I'm a new developer and this is my first time opening an issue on an OS project so please be gentle!

There were no thoughts.

> The Ruby API examples show Filewatcher.new instead of FileWatcher.new

Sorry, `README` in `master` branch is new, as well as [`version.rb`](https://github.com/thomasfl/filewatcher/blob/master/lib/filewatcher/version.rb).

After #61 (the third item of list).

But the gem on the [rubygems.org](https://rubygems.org/) has not been updated for a long time :pensive: 

I hope we'll release it soon.

So, what you described is not a problem. I created the issue specifically about the release of the new version: #74.

And, I think, I can safely close this one.

-----

Temporary possible work-around for `bundle` users:

```ruby
gem 'filewatcher', github: 'thomasfl/filewatcher'
```

**Comment by ngzax** [comment]
FWIW, as a bundle user, the above temporary workaround didn't work, but the following did:

```
gem 'filewatcher', git: 'https://github.com/thomasfl/filewatcher'
```

**Comment by AlexWayfer** [comment]
> FWIW, as a bundle user, the above temporary workaround didn't work

It's weird. Here is what in the [`bundler` documentation](https://bundler.io/v1.15/guides/git.html):

> If you are getting your gems from a public GitHub repository, you can use the shorthand
```ruby
gem 'rack', :github => 'rack/rack'
```

-----

But yes, you can specify git repo also by HTTPS (as above) or SSH (`git@github.com:thomasfl/filewatcher.git`) URL in `:git` option.

**Comment by AlexWayfer** [comment]
Filewatcher 1.0.0 is released! There are no more differences with the `README` from the git-repository.
