### ISSUE TITLE
Pre-stable release with bunch of features

### ISSUE THREAD

**Issue by AlexWayfer** [thomasfl/filewatcher#74]
Despite the planned major changes in the future, we should release a new version of the gem, which includes all the current changes. This is an increase of minor (the second) version, but by a large number (roughly equal to the number of changes made).

**Comment by thomasfl** [comment]
Good, it's about time. What should the new gem version be? The latest release 0.5.4 was pushed to rubygems.org last january.

**Comment by AlexWayfer** [comment]
So, there is small changelog:

* Markdown and code style improvements
* CI fixes and actualization
* Fix event names
* Rename `dontwait` option to `immediate`
* Add `--every` option (now `changes` is a Hash{filename => event} in `watch` block)
* Update and complete tests (including for JRuby and macOS)
* Rename `FileWatcher` to `Filewatcher`

I think, version number should be `0.10.0` (increasing the minor version by 5, as count of features, without tests, but including internal refactoring) or `0.6.0` (just "next").

**Comment by AlexWayfer** [comment]
Also I created and pushed tags for old versions (`0.5.0` – `0.5.4`).

**Comment by thomasfl** [comment]
I'd say it's about time to go for version number 1.0.0. There isn't any major changes in the code. However, all the small changes like "immediate" and "every" option, has so many breaking changes that a major version number increment is in place. The software is more than mature enough after 5 years for a version 1.0.0.

**Comment by AlexWayfer** [comment]
I thought about `1.0.0` release including the plugin system (#71). But it can be `1.x` or `2.0` version (depending on backward-compatibility).

**Comment by thomasfl** [comment]
Yes, a plugin system can be introduced in version 2.0.0.
