### ISSUE TITLE
Doesn't seem to work if repos have a dot in the name

### ISSUE THREAD

**Issue by looeee** [thomasfl/filewatcher#85]
I'm trying to watch https://github.com/mrdoob/three.js, tried the following 

https://github.com/mrdoob/three.js
mrdoob/three.js
github.com/mrdoob/three.js

But each come back with the error "invalid repo name"

**Comment by thomasfl** [comment]
Could you please supply a little more information. For instance, what are the commands you have been running from the commandline?

**Comment by looeee** [comment]
Oops, opened this in the wrong repo. Sorry! 😆
